name: Arduino Compile

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Setup ESP8266 Core
        run: |
          arduino-cli core update-index --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core install esp8266:esp8266 --additional-urls http://arduino.esp8266.com/stable/package_esp8266com_index.json

      - name: Install OLED Library
        run: |
          arduino-cli lib install "ESP8266 and ESP32 OLED driver for SSD1306 displays"

      - name: Compile GM-PRO
        run: |
          arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2 --output-dir ./build ./GM-PRO-ULTIMATE.ino

      - name: Upload Binary Result
        uses: actions/upload-artifact@v4
        with:
          name: GM-PRO-V4-Binary
          path: ./build/*.bin
